[package]
name = "sleepy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
base64 = "0.21.0"
screenshots = "0.5.4"
serde = { version = "1.0", features = ["derive"] } 
tokio = { version = "1.28.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
